# Generated by Django 4.2.5 on 2023-10-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_registration',
            new_name='date_ordered',
        ),
    ]
